name: Test that everything works

on:
  workflow_dispatch:
  push:
    branches:
      - lord
    paths:
      - "**.py"
      - "**.yml"
  pull_request:
    paths:
      - "**.py"
      - "**.yml"
jobs:
  check_types:
    runs-on: ubuntu-latest
    name: Check Types
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: python -m pip install mypy

      - run: python -m mypy soda/*.py --disallow-any-expr --enable-recursive-aliases

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    name: Run Tests

    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -m pip install pytest

      - name: Test
        run: python -m pytest test/
